//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NvhK22cntt3Lession11_2210900031.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NvhCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NvhCategory()
        {
            this.NvhProduct = new HashSet<NvhProduct>();
        }
        [Display(Name ="mã danh mục")]
    
        public int NvhID { get; set; }
        [Display(Name = "tên danh mục")]
        public string NvhCateName { get; set; }
        [Display(Name = "trạng thái")]
        public Nullable<bool> NvhStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NvhProduct> NvhProduct { get; set; }
    }
}
