//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NvhK22cntt3Lession11_2210900031.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NvhProduct
    {
        public string NvhId2210900031 { get; set; }
        public string NvhProName { get; set; }
        public Nullable<int> NvhQty { get; set; }
        public Nullable<double> NvhPrice { get; set; }
        public Nullable<int> NvhCateld { get; set; }
        public Nullable<bool> NvhActive { get; set; }
    
        public virtual NvhCategory NvhCategory { get; set; }
    }
}
